project_name: tf-controller

release:
  prerelease: "true"
  extra_files:
    - glob: config/release/*.yaml

checksum:
  extra_files:
    - glob: config/release/*.yaml

builds:
  - id: tfctl
    main: ./cmd/tfctl
    binary: tfctl
    env:
      - CGO_ENABLED=0
    ldflags:
      -  -X main.BuildSHA={{.ShortCommit}} -X main.BuildVersion={{.Tag}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7

archives:
  - id: tfctl
    builds:
      - tfctl
    name_template: "tfctl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
    format: tar.gz

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source_code"

sboms:
  - id: source
    artifacts: source
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json"

# signs the checksum file
# all files (including the sboms) are included in the checksum
# https://goreleaser.com/customization/sign
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: checksum
    output: true

brews:
  - name: tfctl
    ids:
    - tfctl
    tap:
      owner: weaveworks
      name: homebrew-tap
    commit_author:
      name: weaveworksbot
      email: team+gitbot@weave.works
    folder: Formula
    homepage: https://weaveworks.github.io/tf-controller
    install: |
      bin.install "tfctl"

