apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - manager.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: weaveworks/tf-controller
    newName: ghcr.io/weaveworks/tf-controller
    newTag: v0.9.0-rc.2
