---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: aws-package-v4.33.0
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/tf-controller/aws-primitive-modules
  ref:
    tag: v4.33.0-v1alpha2
