# permissions for end users to edit kustomizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tf-editor-role
rules:
- apiGroups:
  - infra.contrib.fluxcd.io
  resources:
  - terraforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.contrib.fluxcd.io
  resources:
  - terraforms/status
  verbs:
  - get
