{{ if .Values.awsPackage.install }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: aws-package
spec:
  interval: 1h0m0s
  ref:
    tag: {{ .Values.awsPackage.tag }}
  url: oci://{{ .Values.awsPackage.repository }}
{{ end }}
