{{- if .Values.runner.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tf-controller.runner.serviceAccountName" . }}
  labels:
    {{- include "tf-controller.labels" . | nindent 4 }}
  {{- with .Values.runner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
